// Seed data for development (fallback when Supabase not configured)

import type { Category, Product, Promotion } from '@/types/shop';

const ts = new Date().toISOString();

export const seedData = {
  categories: [
    { id: 'cat-etancheite', name: 'Étanchéité & EPDM', slug: 'etancheite-epdm', description: 'Membranes, mastics et systèmes d\'étanchéité pour toitures plates et inclinées', created_at: ts, updated_at: ts },
    { id: 'cat-isolation', name: 'Isolation ITE', slug: 'isolation-ite', description: 'Piliers, kits et accessoires pour isolation de toiture par l\'extérieur', created_at: ts, updated_at: ts },
    { id: 'cat-visserie', name: 'Visserie & Fixations', slug: 'visserie-fixations', description: 'Vis, chevilles, grilles et dispositifs de fixation pour toiture et façade', created_at: ts, updated_at: ts },
    { id: 'cat-colles', name: 'Colles & Mastics', slug: 'colles-mastics', description: 'Colles de contact STRATOGRIP et accessoires d\'application', created_at: ts, updated_at: ts },
    { id: 'cat-entretien', name: 'Entretien toiture', slug: 'entretien-toiture', description: 'Produits de nettoyage, séchage et traitement pour toitures', created_at: ts, updated_at: ts },
    { id: 'cat-accessoires', name: 'Accessoires rives', slug: 'accessoires-rives', description: 'Système Clips & Go 2.0 — finitions rives pour toitures bitumées', created_at: ts, updated_at: ts },
  ] as Category[],

  products: [
    // ── Étanchéité & EPDM ──
    {
      id: 'prod-01', slug: 'mastic-airguard-tyvek',
      title: 'Mastic AirGuard® — TYVEK DUPONT',
      category_id: 'cat-etancheite', brand: 'TYVEK DUPONT',
      description: 'Mastic adhésif pour une liaison élastique permanente et étanche à l\'air des joints et connexions structurelles. Connecte les pare-vapeur à des surfaces telles que la pierre. Excellente adhérence sur béton, plâtre, pierre, plaques de plâtre et bois.',
      avantages: ['Application par cartouche — installation facile', 'Recommandé pour l\'étanchéité à l\'air des couches pare-vapeur AirGuard', 'GEV-Emicode : très faibles émissions de COV', 'Efficacité énergétique améliorée', 'Installable à -5°C'],
      lien_produit: 'https://www.dupontdenemours.fr/products/mastic-airguard.html',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['étanchéité', 'mastic', 'tyvek'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-02', slug: 'bande-tyvek-flexwrap-nf',
      title: 'Bande adhésive DuPont™ Tyvek® FlexWrap™ NF',
      category_id: 'cat-etancheite', brand: 'TYVEK DUPONT',
      description: 'Bande auto-adhésive flexible haute performance pour joint étanche à l\'air et à l\'eau autour des portes, fenêtres, cheminées, entrées de tuyaux. Utilisable intérieur/extérieur. Pose 50% plus rapide que les bandes ordinaires, sans fixation supplémentaire.',
      avantages: ['Meilleure étanchéité à l\'air et à l\'eau que les membranes standard', 'Bande extensible avec doublure séparée en deux — installation facile', 'Pose ~50% plus rapide', 'Résiste aux rayons UV', 'Excellente adhérence sur la plupart des membranes de construction'],
      lien_produit: 'https://www.dupontdenemours.be/fr/products/dupont-tyvek-flexwrap-flashing-tape.html',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['étanchéité', 'bande', 'tyvek'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-03', slug: 'ancrage-photovoltaique-elevate',
      title: 'Ancrage Photovoltaïque Toiture Plate — ELEVATE',
      category_id: 'cat-etancheite', brand: 'ELEVATE',
      description: 'Système de toiture terrasse photovoltaïque durable. Membrane pare-vapeur + couche isolation + membrane d\'étanchéité sur laquelle s\'installent les panneaux solaires. Système avec fixation traversante — étanchéité parfaite autour des points de fixation.',
      avantages: ['Solution toiture PV complète et durable', 'Composants haute qualité pour éviter dépose des panneaux', 'Compatible tous accessoires Elevate'],
      lien_produit: 'https://www.holcimelevate.com/benelux-fr/etancheite-de-toitures/applications/toitures-syst%C3%A8me-photovolta%C3%AFque',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['étanchéité', 'photovoltaïque', 'elevate'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-04', slug: 'rubbergard-epdm-sa-elevate',
      title: 'Elevate RubberGard EPDM SA — Membrane auto-adhésive',
      category_id: 'cat-etancheite', brand: 'ELEVATE',
      description: 'Membrane EPDM auto-adhésive haute performance. Technologie Secure Bond — adhésif appliqué en usine. Installation rapide sans flamme. Durée de vie >50 ans. Résistance exceptionnelle UV, ozone, températures extrêmes. Pose possible jusqu\'à -7°C. Sans solvants et inodore.',
      specs: ['Durée de vie : >50 ans', 'Pose jusqu\'à : -7°C', 'Technologie : Secure Bond (adhésif en usine)', 'Application : toitures plates commerciales, industrielles, végétalisées, PV'],
      lien_produit: 'https://www.holcimelevate.com/benelux-fr/etancheite-de-toitures/epdm/rubbergard-epdm-sa',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['étanchéité', 'epdm', 'elevate'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-05', slug: 'sopraguard-stick-epdm',
      title: 'Sopraguard Stick — Membrane EPDM auto-adhésive SOPREMA',
      category_id: 'cat-etancheite', brand: 'SOPREMA',
      description: 'Membrane EPDM auto-adhésive haute performance. Rouleaux de 30m, épaisseur 1,14mm. Pose propre et rapide sans adhésifs supplémentaires ni outillage complexe. Réduit le temps de mise en œuvre, améliore la productivité sur chantier.',
      specs: ['Format : rouleaux 30m', 'Épaisseur : 1,14mm', 'Application : toitures plates résidentielles, commerciales, industrielles'],
      lien_produit: 'https://sopraguard.com/en/products/sopraguard-stick',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['étanchéité', 'epdm', 'soprema'], created_at: ts, updated_at: ts,
    },

    // ── Isolation ITE ──
    {
      id: 'prod-06', slug: 'pilier-ite-h120',
      title: 'Pilier ITE H120 Support Chevrons — FAYNOT',
      category_id: 'cat-isolation', brand: 'FAYNOT',
      description: 'Pilier Sarking en acier galvanisé à chaud Z275, breveté. Isolation toiture par l\'extérieur sans dérangement intérieur. R = 5,7 m².K/W (200mm isolant total, λ35). Fixation sur tôle métallique ondulée en creux d\'onde. Aucun pont thermique.',
      specs: ['R thermique : 5,7 m².K/W', 'Isolant total : 200mm (λ35)', 'Matériau : acier galvanisé Z275', 'Fixation : tôle ondulée en creux d\'onde'],
      avantages: ['Isolation par l\'extérieur — préserve l\'espace intérieur', 'Aucun pont thermique', 'Système breveté et calculé', 'Compatible tous isolants souples', 'Correction planéité jusqu\'à 40mm', 'Pas de formation spécifique requise'],
      lien_produit: 'https://www.faynot.com/isolation-thermique-exterieur/ite-couverture/piliers-et-accessoires.html',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['isolation', 'ite', 'faynot', 'sarking'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-07', slug: 'pilier-ite-h80',
      title: 'Pilier ITE H80 Support Chevrons — FAYNOT',
      category_id: 'cat-isolation', brand: 'FAYNOT',
      description: 'Pilier Sarking en acier galvanisé à chaud Z275, breveté. R = 4,5 m².K/W (160mm isolant total, λ35). Même principe que H120 pour épaisseur réduite. Fixation sur tôle métallique ondulée en creux d\'onde.',
      specs: ['R thermique : 4,5 m².K/W', 'Isolant total : 160mm (λ35)', 'Matériau : acier galvanisé Z275'],
      lien_produit: 'https://www.faynot.com/isolation-thermique-exterieur/ite-couverture/piliers-et-accessoires.html',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['isolation', 'ite', 'faynot'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-08', slug: 'kit-pilier-ite-h120-vis',
      title: 'Kit ITE H120 + Vis Sarking — FAYNOT',
      category_id: 'cat-isolation', brand: 'FAYNOT',
      description: 'Kit complet : Pilier H120 + Vis tête fraisée Super Bois zinguée Ø8 pour bois (SARKING). R = 5,7 m².K/W. Solution tout-en-un pour chantier rapide.',
      lien_produit: 'https://www.faynot.com/isolation-thermique-exterieur/ite-couverture/piliers-et-accessoires.html',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['isolation', 'kit', 'faynot'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-09', slug: 'kit-pilier-ite-h80-vis',
      title: 'Kit ITE H80 + Vis Sarking — FAYNOT',
      category_id: 'cat-isolation', brand: 'FAYNOT',
      description: 'Kit complet : Pilier H80 + Vis tête fraisée Super Bois zinguée Ø8 pour bois (SARKING). R = 4,5 m².K/W. Solution tout-en-un.',
      lien_produit: 'https://www.faynot.com/isolation-thermique-exterieur/ite-couverture/piliers-et-accessoires.html',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['isolation', 'kit', 'faynot'], created_at: ts, updated_at: ts,
    },

    // ── Visserie & Fixations ──
    {
      id: 'prod-10', slug: 'vis-tete-rivet-p1-faynot',
      title: 'Vis tête rivet autoperceuse P1 Ø6,3×18mm — FAYNOT',
      category_id: 'cat-visserie', brand: 'FAYNOT',
      description: 'Vis autoforeuses P1 Ø6,3×18mm pour fixation tôles et accessoires bardage. Tête Ø9,5mm empreinte Torx T20 — aspect discret comparable à un rivet. Par 100 pièces.',
      specs: ['Diamètre : 6,3mm', 'Longueur : 18mm', 'Tête : Ø9,5mm Torx T20', 'Lot : 100 pièces', 'Épaisseur support : 0,63 à 1mm'],
      avantages: ['Autoperceuse — aucun pré-perçage', 'Capacité perçage : jusqu\'à 4×0,75mm', 'Haute résistance arrachement profils minces', 'Résistance corrosion : inox A2 ou zingué TK12'],
      variants: ['Sans laquage', 'RAL 1015', 'RAL 2001', 'RAL 5008', 'RAL 6011', 'RAL 7006', 'RAL 7015', 'RAL 7016', 'RAL 7022', 'RAL 7037', 'RAL 8012', 'RAL 8014', 'RAL 9002', 'RAL 9005', 'RAL 9006', 'RAL 9007', 'RAL 9010'],
      lien_produit: 'https://www.faynot.com/vis-tr-p1.html',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'faynot', 'autoperceuse'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-11', slug: 'vis-super-bois-sarking-faynot',
      title: 'Vis tête fraisée Super Bois zinguée Ø8 Sarking — FAYNOT',
      category_id: 'cat-visserie', brand: 'FAYNOT',
      description: 'Vis tête fraisée Super Bois zinguée diamètre 8 pour bois (SARKING). Spécialement conçue pour les systèmes ITE couverture.',
      lien_produit: 'https://www.faynot.com/isolation-thermique-exterieur/ite-couverture/piliers-et-accessoires.html',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'faynot', 'sarking'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-12', slug: 'vis-sk-rb-28-20x70-etanco',
      title: 'Vis Sapin SK-RB 28/20×70 — Fixation isolants ETANCO',
      category_id: 'cat-visserie', brand: 'ETANCO',
      description: 'Cheville monobloc à visser en polyamide renforcé fibre de verre. Tête large Ø50mm empreinte carrée 6mm. Pour fixation isolants en rénovation toiture. Pas de pré-perçage, vissage direct dans le bitume.',
      specs: ['Dimensions : 28/20×70', 'Tête : Ø50mm empreinte carrée 6mm', 'Matériau : polyamide renforcé fibre de verre'],
      avantages: ['Pas de pré-perçage', 'Aucune corrosion', 'Aucun pont thermique', 'Excellente tenue mécanique'],
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'etanco', 'isolant'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-13', slug: 'vis-sk-rb-28-40x90-etanco',
      title: 'Vis Sapin SK-RB 28/40×90 — Fixation isolants ETANCO',
      category_id: 'cat-visserie', brand: 'ETANCO',
      description: 'Cheville monobloc à visser en polyamide renforcé fibre de verre. Tête large Ø50mm empreinte carrée 6mm. Dimensions 28/40×90.',
      specs: ['Dimensions : 28/40×90', 'Tête : Ø50mm empreinte carrée 6mm', 'Matériau : polyamide renforcé fibre de verre'],
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'etanco', 'isolant'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-14', slug: 'vis-sk-rb-28-60x110-etanco',
      title: 'Vis Sapin SK-RB 28/60×110 — Fixation isolants ETANCO',
      category_id: 'cat-visserie', brand: 'ETANCO',
      description: 'Cheville monobloc à visser en polyamide renforcé fibre de verre. Dimensions 28/60×110.',
      specs: ['Dimensions : 28/60×110', 'Tête : Ø50mm empreinte carrée 6mm'],
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'etanco', 'isolant'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-15', slug: 'vis-sk-rb-28-120x175-etanco',
      title: 'Vis Sapin SK-RB 28/120×175 — Fixation isolants ETANCO',
      category_id: 'cat-visserie', brand: 'ETANCO',
      description: 'Cheville monobloc à visser en polyamide renforcé fibre de verre. Dimensions 28/120×175 pour isolants épais.',
      specs: ['Dimensions : 28/120×175', 'Tête : Ø50mm empreinte carrée 6mm'],
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'etanco', 'isolant'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-16', slug: 'marcovis-fm-x3-etanco',
      title: 'MARCOVIS FM-X3/PA + Vis TF/Zn — Cheville universelle ETANCO',
      category_id: 'cat-visserie', brand: 'ETANCO',
      description: 'Cheville universelle nylon PA6 haute performance pour applications non structurelles. Tenue jusqu\'à 2000kg à l\'arrachement. Idéale façade, charpente, béton, brique, parpaing, pierre naturelle.',
      specs: ['Matériau cheville : nylon PA6 extra-flexible', 'Tenue arrachement : jusqu\'à 2000kg', 'Applications : béton, béton cellulaire, briques, parpaings, pierre'],
      variants: ['TF/TX30/ZN 10-20/8X60', 'TF/TX30/ZN 30-40/8X80', 'TF/TX30/ZN 50-60/8X100', 'TF/TX30/ZN 70-80/8X120', 'TF/TX40/ZN 10/10X60', 'TF/TX40/ZN 10-30/10X80', 'TF/TX40/ZN 30-50/10X100', 'TF/TX40/ZN 50-70/10X120', 'TF/TX40/ZN 70-90/10X140', 'TF/TX40/ZN 90-110/10X160', 'TF/Tx40/ZN 110-150/10X200', 'TF/Tx40/ZN 140-180/10X230', 'TF/TX40/ZN 170-210/10X260', 'TF/TX40/ZN 200-200/10X290'],
      lien_produit: 'https://www.etanco.fr/MARCOVIS-FM-X3-PA-%2BVis-TF-Zn/p-MA1634',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'etanco', 'cheville'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-17', slug: 'dispositif-anti-pigeons',
      title: 'Dispositif anti-faune / anti-pigeons',
      category_id: 'cat-visserie', brand: 'COMARDEN',
      description: 'Pics métalliques inox sur base polycarbonate. Empêche oiseaux et pigeons de se poser sur toitures, corniches, façades, gouttières, panneaux solaires.',
      specs: ['Base : polycarbonate traité anti-UV', 'Tiges : inox AISI 302, Ø1,3mm', 'Modules : semelles 50cm', 'Densité : 64 pointes/ml', 'Largeur protection : 5 à 7cm'],
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'anti-pigeons', 'accessoire'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-18', slug: 'grille-anti-rongeur-gar-simpson',
      title: 'Grille anti-rongeur GAR — Simpson Strong-Tie',
      category_id: 'cat-visserie', brand: 'SIMPSON STRONG-TIE',
      description: 'Protection bardage ventilé contre rongeurs et insectes. Acier S250GD finition ZPRO — résistance équivalente inox A2. Rouleaux 25m, épaisseur 0,8mm. Conforme DTU 41.2.',
      specs: ['Matériau : acier S250GD finition ZPRO', 'Épaisseur : 0,8mm', 'Longueur rouleau : 25m'],
      variants: ['GAR27/40/25 : tasseau 27mm', 'GAR40/60/25 : double tasseau 30+30mm'],
      lien_produit: 'https://www.simpson.fr/fr-FR/produits/grille-anti-rongeurs-gar',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['visserie', 'simpson', 'grille'], created_at: ts, updated_at: ts,
    },

    // ── Colles & Mastics ──
    {
      id: 'prod-19', slug: 'stratogrip-s110-22l',
      title: 'STRATOGRIP S110 — Colle contact multi-matériaux 22L',
      category_id: 'cat-colles', brand: 'STRATO GRIP',
      description: 'Colle de contact industrielle haute performance. HPL, aluminium, MDF, panneaux particules, contreplaqué. Adhésion instantanée, résistance chaleur 100°C, séchage 1-2 min. Double encollage pour collage permanent.',
      specs: ['Format : 22L', 'Séchage : 1-2 min', 'Résistance température : 100°C', 'Temps ouvert : 40min', 'Rendement : 22L → 200m²', 'Température application : 15-27°C', 'Stockage : 18 mois'],
      warning: 'Non recommandé : vinyles plastifiés, plastiques flexibles, polystyrène EPS/XPS, PE, PP, monochrome',
      lien_produit: 'https://stratogrip.com/wp-content/uploads/2025/09/Fiche-Technique-STRATOGRIP-S110.pdf',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['colle', 'stratogrip', 'multi-matériaux'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-20', slug: 'stratogrip-s163-22l',
      title: 'STRATOGRIP S163 — Colle polyvalente bâtiment/isolation 22L',
      category_id: 'cat-colles', brand: 'STRATO GRIP',
      description: 'Colle ultra high-tack sans chlore pour bâtiment et isolation. Compatible bois, MDF, plastiques rigides, métaux, XPS/EPS, isolants fibre, matériaux minéraux alu. Très long temps ouvert.',
      specs: ['Format : 22L', 'Séchage : 1-2 min', 'Résistance température : 80°C', 'Sans chlore'],
      warning: 'Non recommandé : vinyles plastifiés',
      lien_produit: 'https://stratogrip.com/product/s163/',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['colle', 'stratogrip', 'isolation'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-21', slug: 'stratogrip-m300-22l',
      title: 'STRATOGRIP M300 — Colle mousse et tissu 22L',
      category_id: 'cat-colles', brand: 'STRATO GRIP',
      description: 'Colle industrielle pour cuir, tissus, mousses et revêtements décoratifs. Sellerie, tapisserie, ameublement. Résistance 110°C, séchage 1-2min.',
      specs: ['Format : 22L', 'Séchage : 1-2 min', 'Résistance température : 110°C'],
      warning: 'Non recommandé : vinyles plastifiés, PE, PP, polystyrène, monochrome',
      lien_produit: 'https://stratogrip.com/product/m300/',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['colle', 'stratogrip', 'mousse'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-22', slug: 'pistolet-stratogrip',
      title: 'Pistolet d\'application professionnel STRATOGRIP',
      category_id: 'cat-colles', brand: 'STRATO GRIP',
      description: 'Pistolet professionnel pour bonbonnes STRATOGRIP. Jet réglable 2-25cm, pression 17 bars. Ergonomique et léger. Pas de nettoyage nécessaire. Compatible toutes bonbonnes STRATOGRIP.',
      lien_produit: 'https://stratogrip.com/product/pistolet-dapplication-professionnel/',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['colle', 'stratogrip', 'pistolet'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-23', slug: 'raccord-flexible-stratogrip',
      title: 'Raccord flexible caoutchouc 4m — STRATOGRIP',
      category_id: 'cat-colles', brand: 'STRATO GRIP',
      description: 'Tuyau professionnel ultra souple 4m en caoutchouc haute qualité. Pour applications collage/pulvérisation. Léger, ergonomique, facile à nettoyer.',
      lien_produit: 'https://stratogrip.com/product/raccord-flexible/',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['colle', 'stratogrip', 'accessoire'], created_at: ts, updated_at: ts,
    },

    // ── Entretien toiture ──
    {
      id: 'prod-24', slug: 'poudre-assechante-express',
      title: 'Poudre asséchante toitures plates — EXPRESS (lot 6×1kg)',
      category_id: 'cat-entretien', brand: 'EXPRESS',
      description: 'Absorbe eau de pluie sur toitures plates avant travaux étanchéité bitumineuse. Granulés gonflent au contact de l\'eau et forment un gel. Conditionnée en boîtes 1kg, vendue par lot de 6 pièces. Réf. 848.',
      specs: ['Conditionnement : 1kg × 6 pièces', 'Référence : 848'],
      lien_produit: 'https://www.express.fr/produit/poudre-assechante-848/',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['entretien', 'séchage', 'toiture-plate'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-25', slug: 'rouleau-sechage-toiture',
      title: 'Rouleau de séchage toiture plate',
      category_id: 'cat-entretien', brand: 'IMPORT ALLEMAGNE',
      description: 'Rouleau professionnel en mousse haute absorption pour séchage rapide toitures plates. Largeur 60cm, longueur 130cm, poids ±5,5kg. Eau récupérable par presse sur drain. Fabrication allemande.',
      specs: ['Largeur : 60cm', 'Longueur : 130cm', 'Poids : ±5,5kg', 'Matériau : mousse haute absorption'],
      lien_produit: 'https://www.asphaltequipment.be/fr/rouleau-de-sechage/',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['entretien', 'séchage', 'toiture-plate'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-26', slug: 'algimouss-pro-5l',
      title: 'ALGIMOUSS PRO — Traitement toiture/façade 5L',
      category_id: 'cat-entretien', brand: 'ALGIMOUSS',
      description: 'Traitement professionnel prêt à l\'emploi. Élimine algues, lichens et moisissures. Sans chlore, sans rinçage. Double biocide. Ardoises, tuiles, fibrociment, shingles, crépis, briques, bois, pierres.',
      specs: ['Contenance : 5L', 'Consommation : ~1L/5m²', 'Délai d\'action : 3-9 mois', 'Température application : 5-25°C'],
      avantages: ['Élimine algues, lichens, moisissures', 'Action longue durée', 'Sans chlore et sans rinçage', 'Formule double biocide', 'Recommandé avant peinture'],
      lien_produit: 'https://algimouss.com/produit/anti-mousse-toiture-algimouss-pro/',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['entretien', 'algimouss', 'traitement'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-27', slug: 'algifuge-bois-5l',
      title: 'ALGIFUGE BOIS — Hydrofuge protection bois 5L',
      category_id: 'cat-entretien', brand: 'ALGIMOUSS',
      description: 'Hydrofuge haute performance phase aqueuse sans silicone. Protège bois contre eau, huiles, corps gras, UV, gel. Retarde grisaillement. Terrasses, bardages, palissades, caillebotis, menuiseries, volets, mobilier jardin.',
      specs: ['Contenance : 5L', 'Consommation : ~1L/5m²', 'Séchage : min 12h', 'Température application : 5-25°C'],
      lien_produit: 'https://algimouss.com/produit/hydrofuge-bois-algifuge-bois/',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['entretien', 'algimouss', 'bois'], created_at: ts, updated_at: ts,
    },

    // ── Accessoires rives ──
    {
      id: 'prod-28', slug: 'clips-go-rive-100mm-3m',
      title: 'Clips & Go 2.0 — Rive 100mm × 3m Noir RAL 9005',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Système Roofing Clips — aluminium thermo-laqué. 2 pièces : profilé de base + bourrelet. Finition rives toiture bitumées. Trous oblongs pré-poinçonnés 6×16mm. Compatible revêtements bitumés 4-5mm.',
      specs: ['Matériau : aluminium thermo-laqué', 'Largeur : 100mm', 'Longueur : 3m', 'Couleur : Noir RAL 9005', 'Compatibilité : bitume 4-5mm', 'Joint dilatation : 5mm profilé / 3mm bourrelet'],
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go', 'rive'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-29', slug: 'clips-go-rive-70mm-3m',
      title: 'Clips & Go 2.0 — Rive 70mm × 3m Noir RAL 9005',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Même système que 100mm — version 70mm. Aluminium thermo-laqué, compatible bitume 4-5mm.',
      specs: ['Largeur : 70mm', 'Longueur : 3m', 'Couleur : Noir RAL 9005'],
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go', 'rive'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-30', slug: 'clips-go-arret-100mm',
      title: 'Clips & Go 2.0 — Arrêt 100mm Noir RAL 9005',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Accessoire Clips & Go 2.0 — Arrêt 100mm. Noir RAL 9005.',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-31', slug: 'clips-go-arret-70mm',
      title: 'Clips & Go 2.0 — Arrêt 70mm Noir RAL 9005',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Accessoire Clips & Go 2.0 — Arrêt 70mm. Noir RAL 9005.',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-32', slug: 'clips-go-coin-interieur-100mm',
      title: 'Clips & Go 2.0 — Coin intérieur 100mm 30×30 Noir RAL 9005',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Accessoire Clips & Go 2.0 — Coin intérieur COININT 100mm 30×30. Noir RAL 9005.',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go', 'coin'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-33', slug: 'clips-go-coin-exterieur-100mm',
      title: 'Clips & Go 2.0 — Coin extérieur 100mm 30×30 Noir RAL 9005',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Accessoire Clips & Go 2.0 — Coin extérieur COINEXT 100mm 30×30. Noir RAL 9005.',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go', 'coin'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-34', slug: 'clips-go-raccord-100mm',
      title: 'Clips & Go 2.0 — Raccord 100mm Noir RAL 9005',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Accessoire Clips & Go 2.0 — Raccord STRUC 100mm. Noir RAL 9005.',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-35', slug: 'clips-go-profil-base-3m',
      title: 'Clips & Go 2.0 — Profil de base 3m BRUT',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Accessoire Clips & Go 2.0 — Profilé de base 3m. Couleur : BRUT (non laqué).',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go', 'profil'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-36', slug: 'clips-go-couvre-joint-100mm',
      title: 'Clips & Go 2.0 — Couvre-joint 100mm Noir RAL 9005',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Accessoire Clips & Go 2.0 — Couvre-joint 100mm. Noir RAL 9005.',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go'], created_at: ts, updated_at: ts,
    },
    {
      id: 'prod-37', slug: 'clips-go-easy-corner',
      title: 'Clips & Go 2.0 — Easy Corner BRUT',
      category_id: 'cat-accessoires', brand: 'CLAERHOUT',
      description: 'Accessoire Clips & Go 2.0 — Easy Corner coin. Couleur : BRUT.',
      price_cents: 0, currency: 'EUR', sku: '', stock: 0, is_active: true, images: [], tags: ['accessoire', 'clips-go', 'corner'], created_at: ts, updated_at: ts,
    },
  ] as Product[],

  promotions: [] as Promotion[],
};

/** Slugs of all seed catalogue products — used for image folders & admin upload validation */
export const SEED_PRODUCT_SLUGS: readonly string[] = seedData.products.map((p) => p.slug);
