// Seed data for development (fallback when Supabase not configured)

import type { Category, Product, Promotion } from '@/types/shop';

export const seedData = {
  categories: [
    {
      id: 'cat-1',
      name: 'Toiture',
      slug: 'toiture',
      description: 'Matériaux de couverture pour tous types de toitures',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'cat-2',
      name: 'Charpente',
      slug: 'charpente',
      description: 'Bois de charpente et structures',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'cat-3',
      name: 'Isolation',
      slug: 'isolation',
      description: 'Matériaux d\'isolation thermique et phonique',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'cat-4',
      name: 'Façades',
      slug: 'facades',
      description: 'Matériaux de revêtement de façade',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'cat-5',
      name: 'Étanchéité',
      slug: 'etancheite',
      description: 'Solutions d\'étanchéité pour toitures et terrasses',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'cat-6',
      name: 'Accessoires',
      slug: 'accessoires',
      description: 'Accessoires et fixations',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as Category[],

  products: [
    {
      id: 'prod-1',
      title: 'Tuiles en terre cuite - Modèle Classique',
      slug: 'tuiles-terre-cuite-classique',
      description: 'Tuiles en terre cuite de qualité supérieure, résistantes aux intempéries. Idéales pour les toitures traditionnelles.',
      price_cents: 12500, // 125.00 EUR
      currency: 'EUR',
      sku: 'TTC-CL-001',
      stock: 1500,
      is_active: true,
      category_id: 'cat-1',
      images: ['/images/products/tuile-1.jpg'],
      tags: ['toiture', 'terre-cuite', 'traditionnel'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-2',
      title: 'Ardoises naturelles - Format 30x20',
      slug: 'ardoises-naturelles-30x20',
      description: 'Ardoises naturelles belges, format standard 30x20 cm. Excellente durabilité et esthétique authentique.',
      price_cents: 18500,
      currency: 'EUR',
      sku: 'ARD-NAT-30x20',
      stock: 800,
      is_active: true,
      category_id: 'cat-1',
      images: ['/images/products/ardoise-1.jpg'],
      tags: ['toiture', 'ardoise', 'naturel'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-3',
      title: 'Laine de roche - Panneaux 1200x600',
      slug: 'laine-de-roche-panneaux-1200x600',
      description: 'Panneaux d\'isolation en laine de roche, épaisseur 100mm. Performance thermique et phonique optimale.',
      price_cents: 3200,
      currency: 'EUR',
      sku: 'LR-PAN-100',
      stock: 250,
      is_active: true,
      category_id: 'cat-3',
      images: ['/images/products/laine-roche-1.jpg'],
      tags: ['isolation', 'thermique', 'phonique'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-4',
      title: 'Bardage bois - Mélèze traité',
      slug: 'bardage-bois-meleze-traite',
      description: 'Lames de bardage en mélèze traité autoclave, classe 4. Dimensions 145x20mm, longueur 3m.',
      price_cents: 1850,
      currency: 'EUR',
      sku: 'BARD-MEL-145',
      stock: 1200,
      is_active: true,
      category_id: 'cat-4',
      images: ['/images/products/bardage-1.jpg'],
      tags: ['façade', 'bois', 'bardage'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-5',
      title: 'Membrane d\'étanchéité EPDM - 1.5mm',
      slug: 'membrane-etancheite-epdm-15mm',
      description: 'Membrane d\'étanchéité EPDM noire, épaisseur 1.5mm. Pour toitures plates et terrasses.',
      price_cents: 1250,
      currency: 'EUR',
      sku: 'EPDM-1.5',
      stock: 500,
      is_active: true,
      category_id: 'cat-5',
      images: ['/images/products/epdm-1.jpg'],
      tags: ['étanchéité', 'toiture-plate', 'terrasse'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-6',
      title: 'Poutres en chêne - Section 200x200',
      slug: 'poutres-chene-200x200',
      description: 'Poutres en chêne massif, section 200x200mm, longueur 4m. Pour charpentes traditionnelles.',
      price_cents: 45000,
      currency: 'EUR',
      sku: 'POUT-CHENE-200',
      stock: 45,
      is_active: true,
      category_id: 'cat-2',
      images: ['/images/products/poutre-1.jpg'],
      tags: ['charpente', 'bois', 'chêne'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-7',
      title: 'Laine de verre - Rouleaux 1200mm',
      slug: 'laine-de-verre-rouleaux-1200mm',
      description: 'Rouleaux d\'isolation en laine de verre, épaisseur 200mm. Performance thermique R=5.0 m².K/W.',
      price_cents: 2800,
      currency: 'EUR',
      sku: 'LV-ROL-200',
      stock: 180,
      is_active: true,
      category_id: 'cat-3',
      images: ['/images/products/laine-verre-1.jpg'],
      tags: ['isolation', 'thermique'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-8',
      title: 'Bardage composite - Gris anthracite',
      slug: 'bardage-composite-gris-anthracite',
      description: 'Lames de bardage composite, couleur gris anthracite. Dimensions 150x22mm, longueur 4m. Sans entretien.',
      price_cents: 3200,
      currency: 'EUR',
      sku: 'BARD-COMP-GRIS',
      stock: 600,
      is_active: true,
      category_id: 'cat-4',
      images: ['/images/products/bardage-comp-1.jpg'],
      tags: ['façade', 'composite', 'sans-entretien'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-9',
      title: 'Crochets à ardoise - Inox',
      slug: 'crochets-ardoise-inox',
      description: 'Crochets de fixation pour ardoises, en inox 304. Longueur 100mm. Paquet de 50 unités.',
      price_cents: 4500,
      currency: 'EUR',
      sku: 'CROCH-ARD-INOX',
      stock: 2500,
      is_active: true,
      category_id: 'cat-6',
      images: ['/images/products/crochet-1.jpg'],
      tags: ['accessoire', 'fixation', 'ardoise'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-10',
      title: 'Tuiles photovoltaïques - Intégration invisible',
      slug: 'tuiles-photovoltaiques-integration',
      description: 'Tuiles solaires intégrées, puissance 50W par tuile. Esthétique identique aux tuiles classiques.',
      price_cents: 125000,
      currency: 'EUR',
      sku: 'TUILE-PV-50W',
      stock: 120,
      is_active: true,
      category_id: 'cat-1',
      images: ['/images/products/tuile-pv-1.jpg'],
      tags: ['toiture', 'solaire', 'photovoltaïque'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-11',
      title: 'Isolation PIR - Panneaux 1200x600',
      slug: 'isolation-pir-panneaux-1200x600',
      description: 'Panneaux d\'isolation rigide PIR, épaisseur 100mm. Haute performance thermique, résistant à l\'humidité.',
      price_cents: 4200,
      currency: 'EUR',
      sku: 'PIR-PAN-100',
      stock: 320,
      is_active: true,
      category_id: 'cat-3',
      images: ['/images/products/pir-1.jpg'],
      tags: ['isolation', 'rigide', 'haute-performance'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'prod-12',
      title: 'Chevrons en épicéa - 63x175mm',
      slug: 'chevrons-epicea-63x175mm',
      description: 'Chevrons en épicéa traité, section 63x175mm, longueur 4m. Pour charpentes et ossatures.',
      price_cents: 850,
      currency: 'EUR',
      sku: 'CHEV-EPI-63x175',
      stock: 800,
      is_active: true,
      category_id: 'cat-2',
      images: ['/images/products/chevron-1.jpg'],
      tags: ['charpente', 'bois', 'ossature'],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as Product[],

  promotions: [
    {
      id: 'promo-1',
      title: 'Réduction hiver - Isolation',
      code: 'HIVER2024',
      description: '10% de réduction sur tous les produits d\'isolation',
      discount_type: 'percent',
      discount_value: 10,
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as Promotion[],
};
